mysql:
  host: localhost
  port: 3306
  user: root
  password: password
  database: quests
series: 1
streak_multiplier: 0.025
cycle_multiplier: 0.05
quest_lifespan: 5
broadcast_completions: true
rewards:
  cycle_complete:
  - text: Enjoy your special reward %happy%
    command: give %player% beacon 1
  streak_of_5:
  - text: You're on a roll! Enjoy this diamond %happy%
    command: give %player% diamond 1
