mysql:
  host: localhost
  port: 3306
  user: root
  password: password
  database: quests
series: 1
soft_launch: true
cycle_multiplier: 0.05
streak_bonus_cap: 100
streak_bonus_increment: 1
quest_lifespan: 5
quest_cooldown_factor: 2.0
broadcast_completions: true
title_on_completion: true
rewards:
  cycle_complete:
  - text: Enjoy your special reward %happy%
    command: give %player% beacon 1
  streak_of_5:
  - text: You're on a roll! Enjoy this diamond %happy%
    command: give %player% diamond 1
  completed_5_quests:
  - text: You have completed 5 quests! Amazing!
    command: give %player% minecraft:fish 1 3