name: Quests
main: io.github.feydk.Quests.QuestsPlugin
description: Quests will create a quest for you every day. Completing a quest will earn you a reward.
database: true
depend: [ Vault, Fe ]
version: 1.0
commands:
  quest:
    description: Use the quest commands
    permission: quests.quest
    aliases: q
    usage: |-
      /quest - See info about current quest
      /quest cancel - Cancel quest
      /quest me - See your personal stats
  questadmin:
    description: Use helper commands, mainly used for testing
    permission: quests.admin
    aliases: qa
    usage: |-
      /questadmin new <id> - Force creation of a new quest if player has no active quest (id is optional)
      /questadmin complete - Force completion of current active quest
      /questadmin reset - Wipe all stats and progress and start from scratch at tier 1
      /questadmin check - Validate that all quest configs have valid json
permissions:
  quests.quests:
    description: Use /quests
    default: op
  quests.quest:
    description: Use /quest
    default: op
  quests.admin:
    description: Use /questadmin
    default: op